springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8080}

petstore:
  service:
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}
    app:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}


  cosmosdb:
    database:
      name: petstore-eastus-cosmosdb-db
    container:
      name: order
    account:
      host: ${COSMOSDB_ACCOUNT_HOST}
      key: ${COSMOSDB_ACCOUNT_KEY}

spring:
  application:
    name: petstoreorderservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
