springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8080}

petstore:
  service:
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}

spring:
  application:
    name: petstoreorderservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  azure:
    cosmosdb:
      uri: https://petapp-cosmosdb.documents.azure.com:443/
      key: zuLUNW6Hws4WaXz3Xgv1Wmem6h0N1Q3VAXX2vD7EatHyNZ3VnxxLMZ3G1x5ofjRG5R5ukLELbpeFACDbXJ9RHw==
      secondaryKey: zo2Gc3J8RupKbaP3YYnJ0zDibLG9bSvswLyIwoAzU1Unx3dXCVCz03irs0cqjljsANSPbKXs0XMtACDbUkkEKw==
      database: ToDoList

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
