springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8080}

petstore:
  service:
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}
    orderreservationfn:
      url: ${ORDERRESERVATIONFN_URL:http://localhost:8071/api/OrderItemsReserver}

azure:
  servicebus:
    connection-string: Endpoint=sb://petapp-event-bus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=Dsd4YtSu+jzlpIJyfsCUE1ZkJdk7S2Cc9+ASbAgCW3Y=
    queue-name: queue1

spring:
  application:
    name: petstoreorderservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
